### ISSUE TITLE
Correctifs Annuaire 21/03 à intégrer

### ISSUE THREAD

**Issue by laetitiaGabreau** [SocialGouv/mon-psy-sante#106]
Dans texte introductif (du haut):
- Plus de 1000 psychologues ont candidaté... [Marine]
- Alléger les premières phases (redondance "psychologue partenaires") [Marine]

Texte dans encadré rose
- tester phrase sur "souhait d'accueillir des enfants/adolescents" [à tester avec utilisateurs laetitia]
- remplacer "A lire..." par "A NOTER" de manière plus générique et pour la dernière phrase, transformer en bullet point sans le "je"

Picto :
- langue
- public (quand on passe sur le picto, un texte s'affiche "le psychologue souhaite accueillir..;"

Formater nom/prénom (tout en majuscules)

Affichage carte
50 premiers, et si pas de psy à moins de 100 km, mettre un texte d'info et avoir la possibilité de dézoomer pour voir les psy dispo

Deux dossiers avec problème dans adresse

**Comment by carolineBda** [comment]
TODO Caro :


Picto :
- [ ] tel / email / adresse / site ?
- [ ] langue (vérifier si plusieurs langues que ça s'affiche bien + vérifier l'import des langues)
- [ ] public (quand on passe sur le picto, un texte s'affiche "le psychologue souhaite accueillir..;"

- [ ] Formater nom/prénom (tout en majuscules)

- [ ] Affichage carte
50 premiers, et si pas de psy à moins de 100 km, mettre un texte d'info et avoir la possibilité de dézoomer pour voir les psy dispo
- [ ] voir possibilité de dézoomer dans le cas du dessus
