### ISSUE TITLE
Validation automatique des dossiers (pour fin février-début mars)

### ISSUE THREAD

**Issue by laetitiaGabreau** [SocialGouv/mon-psy-sante#56]
Dossier test : 7780822

**Comment by carolineBda** [comment]
Pour vérifier le numéro Adeli, on peut utiliser l'API déployé par Sante Psy Etudiant : https://github.com/betagouv/sante-psy/blob/main/README_api_sant%C3%A9.md

A noté qu'Adeli met en place une API mais au format FHIR.
https://esante.gouv.fr/sites/default/files/media_entity/documents/annuaire_interrogation-synchrone-v1_dsft_2020_06-30_v1.0.pdf
