### ISSUE TITLE
Rechercher les coordonnées d'un psy 1/4

### ISSUE THREAD

**Issue by oscarlefebvre** [SocialGouv/mon-psy-sante#66]
**En tant que patient**, je souhaite rechercher un psychologue partenaire par **sa localisation** afin de trouver le plus proche de chez moi (Version 1/3)

# Contexte #
Rechercher un psychologue proche d'une adresse (domicile, travail, ...). Pouvoir saisir un code postal, une ville, et identifier les psychologues proches de cette adresse par ses coordonnées écrites et via une carte (map) de géolocalisation. 
_Vu le 22/02 avec dev, recherche par adresse = compliquée / à développer plus tard ?_

# Info
- **un champ de recherche  et une page d'affichage**
Une page avec le champ de recherche : le code postal, la ville, (le département?)
Une fois le lieu saisi, une page d'affichage avec les résultats :

- > une carte (map) géolocalisant les psychologues proches de l'adresse sur un périmètre pouvant d'élargir de la rue, à la ville, puis au département (pour les lieux où il y a peu de psychologues partenaires) 

- > Chaque psychologue est identifié par un icône sur la carte map)

- > la fiche contact de chaque psychologue est visible avec nom, prénom, adresse du cabinet, numéro de téléphone, email pro si souhaité, site web éventuellement, langues parlées, possibilité de séances à distance, public(s) pris en charge, nom du CDS ou de la MSP si activité salariée. 

- Quand on clique sur un icône représentant un psy sur la carte, sa fiche contact est highlitée (encadré, fond de couleur, ?) 

- **Update** : 

- > les nouveaux psy => une mise à jour au fil de l'eau du conventionnement de nouveaux psy partenaires (quand "acceptés" sur DS)

- > les mises à jour de données des fiches contact => administration à la main de chaque CPAM (périmètre local) qui peut modifier des informations dans la fiche contact [ou supprimer des psy - à vérifier car lien avec DS]-  cf. feature "Administration de l'annuaire"

- **View**:

- > Une fois ville ou CP saisi,  une page de résultats apparaît avec, sur une partie de l'écran la carte (map) de géolocalisation, et sur une autre partie (en face à face), les fiches contacts du périmètre concerné. 

- Si on clique sur l'icône représentant un psy sur la carte, on a un highlighter sur la fiche contact (encadré de couleur ou fond de couleur) ou seule la fiche contact apparaît ??? > à arbitrer avec dev

**Comment by carolineBda** [comment]
TODO:
- [ ] encadré plus visible quand on click sur un psy
- [ ] changer la couleur du point sur la carte quand un psy est sélectionné
- [ ] après une recherche : zoom out carte pour voir au moins un point

**Comment by laetitiaGabreau** [comment]
Test utilisateurs faits le 24/03 - laetitia (nouvelles cards en conséquence)
Point avec Marine à arbitrer :
- [ ] si pas de psychologue à moins de 50 km, afficher le message d'alerte (et non plus 100km)
- [ ] Retirer filtre : adultes / ado-enfants / adultes ou ado-enfants et mettre un bouton (comme pour la visio) pour cocher "enfants-ado". Par défaut, tout s'affiche
- [ ] Préciser qu'il s'agit d'un annuaire et que la prise de rendez-vous ne se fait pas sur le site mais via les coordonnées laissées par le psychologue (dans intro et dans les fiches contacts ?)
- [ ] Rappeler dans la lettre à la communauté des psy de nous prévenir quand indisponibles pour les masquer (LG le note dans le board de Notion)
