### ISSUE TITLE
Rechercher un psy avec des filtres 2/4

### ISSUE THREAD

**Issue by laetitiaGabreau** [SocialGouv/mon-psy-sante#69]
**En tant que** patient, 
**je souhaite** rechercher un psychologue partenaire selon son profil, à partir d'un filtre "séance à distance" 
**afin de** trouver un psychologue qui accepte de faire des consultations à distance. 

**En tant que** patient, 
**je souhaite** rechercher un psychologue partenaire selon son profil, à partir du filtre "type de public" 
**afin de** trouver un psychologue qui est spécialisé dans les enfants ou dans les adultes

# Contexte #
Rechercher un psychologue qui répond à ma situation et mes attentes :  spécialisé enfants/adultes, faire des visio car je suis éloigné. 

# Info
**Read** : les champs de recherche restent les mêmes (nom et/ou lieu d'exercice), une page d'affichage des résultats
Sur la page de résultats : présence de 2 filtres (possible de n'en choisir qu'un, ou deux, ou les trois)

1. possibilité de séances à distance (Oui/non)
2. public(s) pris en charge  (Adultes, Adultes et enfants/adolescents, Enfants/Adolescents)

**View**:

- > Une fois les filtres sélectionnés, les fiches contacts correspondantes s'affichent sur la page

**Comment by carolineBda** [comment]
TODO
- [ ] lancé la recherche des qu'on change un filtre ?
